# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'zach@yestrak.com'
  config.password       = '321yestrak'
  config.integrator_key = 'YEST-f0049ef9-b611-4fe0-8685-4a40fcaca3e0'
  config.account_id     = '615928'
  #config.endpoint       = 'https://www.docusign.net/restapi'
  #config.api_version    = 'v1'

  #config.username = 'mayank.jani@softwebsolutions.com'
  #config.password = 'mayank14'
  #config.integrator_key = 'TEST-ae79745c-d10b-4e95-9edc-d938fa24c5de'
  #config.account_id = '483548'
  #config.endpoint = 'https://www.docusign.net/restapi'
  #config.api_version = 'v1'
end
