development: &default

  # Credentials for REST APIs
  client_id: EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
  client_secret: EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: mayank.jani_api1.softwebsolutions.com
  password: 1404117867
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AXwxONT4YKtOC55jLxw2Kuz2XXZT
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: mayank.jani@softwebsolutions.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

staging:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  mode: live
